version: '3.8'

services:
  khaja-ajmir-traders:
    build:
      context : .
      dockerfile : Dockerfile
    container_name: khaja-ajmir-traders
    ports:
      - "4000:8080"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL = mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/Khaja_Ajmir_Traders
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
    volumes:
      - .:/app
      - /app/node_modules/bcrypt/
      - mongoDbData:/data/db
    networks:
      - app_network
    depends_on:
      - mongo_db
      - rabbit_mq

  mongo_db:
    image: mongo:latest
    container_name: mongoDb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL = mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/Khaja_Ajmir_Traders
    volumes:
      - mongoDbData:/data/db
    networks:
      - app_network

  rabbit_mq:
    image: rabbitmq
    container_name: rabbit_mq
    ports:
      - "15672:15672"
    networks:
      - app_network


volumes:
  mongoDbData:
    driver : local

networks:
  app_network :
    driver : bridge
